# Generated by Django 2.2.14 on 2020-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_locations', '0007_remove_driverrickshaw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrickshaw',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
