# Generated by Django 2.2.14 on 2020-07-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_locations', '0008_driverrickshaw_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
