# Generated by Django 2.2.14 on 2020-07-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_locations', '0005_auto_20200719_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRickshaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rickshaw_number', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rickshaw_id', to='accounts_locations.User')),
            ],
        ),
    ]
