# Generated by Django 2.2.14 on 2020-07-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_locations', '0006_driverrickshaw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverrickshaw',
            name='status',
        ),
    ]
